version: '3.3'
services:
  user:
    build: .
    container_name: 'user'
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - main

networks:
  main:
    external:
      name: main-network